export interface Field {
  id: string
  name: string
}

export interface Major {
  id: string
  name: string
  fields: Field[]
}

export interface Internship {
  id: string
  company: string
  majorId: string
  fieldId: string
  major: string
  field: string
  location: string
  description: string
  duration: string
  type: string
}

export const majors: Major[] = [
  {
    id: "software-engineer",
    name: "Software Engineering",
    fields: [
      { id: "web-dev", name: "Web Development" },
      { id: "mobile-dev", name: "Mobile Development" },
      { id: "backend", name: "Backend Development" },
      { id: "devops", name: "DevOps & Cloud" },
      { id: "ai-ml", name: "AI & Machine Learning" },
    ],
  },
  {
    id: "culinary",
    name: "Culinary Arts",
    fields: [
      { id: "pastry", name: "Pastry & Baking" },
      { id: "cuisine", name: "International Cuisine" },
      { id: "kitchen-mgmt", name: "Kitchen Management" },
      { id: "food-safety", name: "Food Safety & Hygiene" },
      { id: "menu-planning", name: "Menu Planning & Design" },
    ],
  },
  {
    id: "tourism",
    name: "Tourism Service Business",
    fields: [
      { id: "tour-guide", name: "Tour Guiding" },
      { id: "travel-planning", name: "Travel Planning" },
      { id: "events-mgmt", name: "Events Management" },
      { id: "customer-service", name: "Customer Service" },
      { id: "destination-mgmt", name: "Destination Management" },
    ],
  },
  {
    id: "hotel-accommodation",
    name: "Hotel Accommodation",
    fields: [
      { id: "front-desk", name: "Front Desk Operations" },
      { id: "housekeeping", name: "Housekeeping Management" },
      { id: "food-beverage", name: "Food & Beverage Service" },
      { id: "hotel-mgmt", name: "Hotel Management" },
      { id: "guest-relations", name: "Guest Relations" },
    ],
  },
]

export const internshipData: Internship[] = [
  // Software Engineer - Web Development
  {
    id: "1",
    company: "TechVision Indonesia",
    majorId: "software-engineer",
    fieldId: "web-dev",
    major: "Software Engineering",
    field: "Web Development",
    location: "Jakarta, Indonesia",
    description:
      "Build modern web applications using React and Node.js. Work with experienced developers on real-world projects.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "2",
    company: "WebFlow Studios",
    majorId: "software-engineer",
    fieldId: "web-dev",
    major: "Software Engineering",
    field: "Web Development",
    location: "Bandung, Indonesia",
    description:
      "Develop responsive web interfaces and backend APIs. Gain experience with modern development tools and practices.",
    duration: "2 months",
    type: "Paid",
  },
  {
    id: "3",
    company: "Digital Innovation Labs",
    majorId: "software-engineer",
    fieldId: "web-dev",
    major: "Software Engineering",
    field: "Web Development",
    location: "Surabaya, Indonesia",
    description: "Contribute to full-stack web projects. Learn best practices in code quality and collaboration.",
    duration: "3 months",
    type: "Unpaid",
  },

  // Software Engineer - Mobile Development
  {
    id: "4",
    company: "MobileFirst Apps",
    majorId: "software-engineer",
    fieldId: "mobile-dev",
    major: "Software Engineering",
    field: "Mobile Development",
    location: "Jakarta, Indonesia",
    description: "Develop iOS and Android applications. Work on features that millions of users will interact with.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "5",
    company: "AppNation",
    majorId: "software-engineer",
    fieldId: "mobile-dev",
    major: "Software Engineering",
    field: "Mobile Development",
    location: "Yogyakarta, Indonesia",
    description: "Create native mobile applications. Mentor from senior developers and build your portfolio.",
    duration: "2 months",
    type: "Paid",
  },
  {
    id: "6",
    company: "CrossPlatform Studios",
    majorId: "software-engineer",
    fieldId: "mobile-dev",
    major: "Software Engineering",
    field: "Mobile Development",
    location: "Medan, Indonesia",
    description: "Build cross-platform applications using Flutter. Collaborate with design and product teams.",
    duration: "3 months",
    type: "Paid",
  },

  // Software Engineer - Backend Development
  {
    id: "7",
    company: "CloudCore Systems",
    majorId: "software-engineer",
    fieldId: "backend",
    major: "Software Engineering",
    field: "Backend Development",
    location: "Jakarta, Indonesia",
    description:
      "Work on scalable backend systems and APIs. Develop skills in database design and server architecture.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "8",
    company: "DataFlow Technologies",
    majorId: "software-engineer",
    fieldId: "backend",
    major: "Software Engineering",
    field: "Backend Development",
    location: "Bogor, Indonesia",
    description: "Build high-performance backend services. Work with microservices and distributed systems.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "9",
    company: "Enterprise Solutions Ltd",
    majorId: "software-engineer",
    fieldId: "backend",
    major: "Software Engineering",
    field: "Backend Development",
    location: "Bandung, Indonesia",
    description: "Develop enterprise-grade backend solutions. Learn about system design and performance optimization.",
    duration: "2 months",
    type: "Unpaid",
  },

  // Software Engineer - DevOps
  {
    id: "10",
    company: "Infrastructure Pro",
    majorId: "software-engineer",
    fieldId: "devops",
    major: "Software Engineering",
    field: "DevOps & Cloud",
    location: "Jakarta, Indonesia",
    description: "Deploy and maintain cloud infrastructure. Work with Docker, Kubernetes, and CI/CD pipelines.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "11",
    company: "Cloud Native Experts",
    majorId: "software-engineer",
    fieldId: "devops",
    major: "Software Engineering",
    field: "DevOps & Cloud",
    location: "Surabaya, Indonesia",
    description: "Manage cloud platforms and automate deployment processes. Ensure system reliability and security.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "12",
    company: "DevOps Academy",
    majorId: "software-engineer",
    fieldId: "devops",
    major: "Software Engineering",
    field: "DevOps & Cloud",
    location: "Bandung, Indonesia",
    description: "Learn DevOps practices in a collaborative environment. Work on real infrastructure projects.",
    duration: "2 months",
    type: "Unpaid",
  },

  // Software Engineer - AI & ML
  {
    id: "13",
    company: "AI Research Labs",
    majorId: "software-engineer",
    fieldId: "ai-ml",
    major: "Software Engineering",
    field: "AI & Machine Learning",
    location: "Jakarta, Indonesia",
    description: "Work on cutting-edge AI and machine learning projects. Implement neural networks and data models.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "14",
    company: "Data Science Studios",
    majorId: "software-engineer",
    fieldId: "ai-ml",
    major: "Software Engineering",
    field: "AI & Machine Learning",
    location: "Yogyakarta, Indonesia",
    description:
      "Build machine learning models for real-world problems. Work with large datasets and advanced algorithms.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "15",
    company: "Innovation AI Center",
    majorId: "software-engineer",
    fieldId: "ai-ml",
    major: "Software Engineering",
    field: "AI & Machine Learning",
    location: "Medan, Indonesia",
    description: "Apply machine learning to business challenges. Collaborate with data scientists and engineers.",
    duration: "2 months",
    type: "Unpaid",
  },

  // Culinary - Pastry & Baking
  {
    id: "16",
    company: "Artisan Bakery & Patisserie",
    majorId: "culinary",
    fieldId: "pastry",
    major: "Culinary Arts",
    field: "Pastry & Baking",
    location: "Jakarta, Indonesia",
    description: "Learn pastry and baking techniques from expert pastry chefs. Create artisanal breads and desserts.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "17",
    company: "Sweet Dreams Bakery",
    majorId: "culinary",
    fieldId: "pastry",
    major: "Culinary Arts",
    field: "Pastry & Baking",
    location: "Bandung, Indonesia",
    description: "Master cake decoration and pastry production. Work in a fast-paced bakery environment.",
    duration: "2 months",
    type: "Paid",
  },
  {
    id: "18",
    company: "Professional Pastry Academy",
    majorId: "culinary",
    fieldId: "pastry",
    major: "Culinary Arts",
    field: "Pastry & Baking",
    location: "Surabaya, Indonesia",
    description: "Develop advanced pastry skills. Learn about ingredients, techniques, and food presentation.",
    duration: "3 months",
    type: "Unpaid",
  },

  // Culinary - International Cuisine
  {
    id: "19",
    company: "Global Flavors Restaurant",
    majorId: "culinary",
    fieldId: "cuisine",
    major: "Culinary Arts",
    field: "International Cuisine",
    location: "Jakarta, Indonesia",
    description: "Cook international dishes and learn fusion cuisine. Experience diverse culinary traditions.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "20",
    company: "World Kitchen Dining",
    majorId: "culinary",
    fieldId: "cuisine",
    major: "Culinary Arts",
    field: "International Cuisine",
    location: "Bali, Indonesia",
    description: "Prepare authentic dishes from various cuisines. Train under experienced international chefs.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "21",
    company: "Culinary Fusion Lab",
    majorId: "culinary",
    fieldId: "cuisine",
    major: "Culinary Arts",
    field: "International Cuisine",
    location: "Yogyakarta, Indonesia",
    description: "Create innovative international dishes. Learn about global ingredients and cooking methods.",
    duration: "2 months",
    type: "Paid",
  },

  // Culinary - Kitchen Management
  {
    id: "22",
    company: "Professional Kitchen Management",
    majorId: "culinary",
    fieldId: "kitchen-mgmt",
    major: "Culinary Arts",
    field: "Kitchen Management",
    location: "Jakarta, Indonesia",
    description: "Oversee kitchen operations and staff. Learn about food safety, inventory, and efficiency.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "23",
    company: "Restaurant Management Group",
    majorId: "culinary",
    fieldId: "kitchen-mgmt",
    major: "Culinary Arts",
    field: "Kitchen Management",
    location: "Surabaya, Indonesia",
    description: "Manage kitchen teams and coordinate service. Ensure quality and consistency.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "24",
    company: "Hospitality Leaders Institute",
    majorId: "culinary",
    fieldId: "kitchen-mgmt",
    major: "Culinary Arts",
    field: "Kitchen Management",
    location: "Bandung, Indonesia",
    description: "Learn kitchen leadership and management skills. Work with professional kitchen teams.",
    duration: "2 months",
    type: "Unpaid",
  },

  // Culinary - Food Safety & Hygiene
  {
    id: "25",
    company: "SafeFood International",
    majorId: "culinary",
    fieldId: "food-safety",
    major: "Culinary Arts",
    field: "Food Safety & Hygiene",
    location: "Jakarta, Indonesia",
    description: "Ensure food safety standards and compliance. Learn hygiene practices and certification.",
    duration: "2 months",
    type: "Paid",
  },
  {
    id: "26",
    company: "Quality Assurance Culinary",
    majorId: "culinary",
    fieldId: "food-safety",
    major: "Culinary Arts",
    field: "Food Safety & Hygiene",
    location: "Medan, Indonesia",
    description: "Implement food safety protocols in restaurants. Monitor and improve hygiene standards.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "27",
    company: "Culinary Health Standards",
    majorId: "culinary",
    fieldId: "food-safety",
    major: "Culinary Arts",
    field: "Food Safety & Hygiene",
    location: "Yogyakarta, Indonesia",
    description: "Learn food handling and contamination prevention. Become a certified food safety professional.",
    duration: "2 months",
    type: "Unpaid",
  },

  // Culinary - Menu Planning
  {
    id: "28",
    company: "Creative Culinary Designs",
    majorId: "culinary",
    fieldId: "menu-planning",
    major: "Culinary Arts",
    field: "Menu Planning & Design",
    location: "Jakarta, Indonesia",
    description: "Design menus and plan seasonal dishes. Balance nutrition, cost, and customer preferences.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "29",
    company: "Restaurant Concept Kitchen",
    majorId: "culinary",
    fieldId: "menu-planning",
    major: "Culinary Arts",
    field: "Menu Planning & Design",
    location: "Bali, Indonesia",
    description: "Create menus for diverse restaurants and events. Develop unique dishes and presentations.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "30",
    company: "Food Innovation Studio",
    majorId: "culinary",
    fieldId: "menu-planning",
    major: "Culinary Arts",
    field: "Menu Planning & Design",
    location: "Surabaya, Indonesia",
    description: "Plan menus for restaurants and catering services. Work with chefs and nutritionists.",
    duration: "2 months",
    type: "Unpaid",
  },

  // Tourism - Tour Guiding
  {
    id: "31",
    company: "Adventure Tours Indonesia",
    majorId: "tourism",
    fieldId: "tour-guide",
    major: "Tourism Service Business",
    field: "Tour Guiding",
    location: "Bali, Indonesia",
    description: "Guide tourists through cultural and natural attractions. Share knowledge about destinations.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "32",
    company: "Heritage & Culture Tours",
    majorId: "tourism",
    fieldId: "tour-guide",
    major: "Tourism Service Business",
    field: "Tour Guiding",
    location: "Yogyakarta, Indonesia",
    description: "Lead cultural tours and share local history. Engage with diverse international groups.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "33",
    company: "Eco-Tourism Guides",
    majorId: "tourism",
    fieldId: "tour-guide",
    major: "Tourism Service Business",
    field: "Tour Guiding",
    location: "Flores, Indonesia",
    description: "Guide nature and eco-tourism experiences. Promote sustainable tourism practices.",
    duration: "2 months",
    type: "Unpaid",
  },

  // Tourism - Travel Planning
  {
    id: "34",
    company: "World Travel Planners",
    majorId: "tourism",
    fieldId: "travel-planning",
    major: "Tourism Service Business",
    field: "Travel Planning",
    location: "Jakarta, Indonesia",
    description: "Create travel itineraries and plan trips. Assist clients in booking accommodations and activities.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "35",
    company: "Destination Dreams Travel",
    majorId: "tourism",
    fieldId: "travel-planning",
    major: "Tourism Service Business",
    field: "Travel Planning",
    location: "Bandung, Indonesia",
    description: "Plan customized travel experiences. Manage bookings and coordinate with service providers.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "36",
    company: "Adventure Planning Co",
    majorId: "tourism",
    fieldId: "travel-planning",
    major: "Tourism Service Business",
    field: "Travel Planning",
    location: "Surabaya, Indonesia",
    description: "Design adventure and travel packages. Work with hotels and tour operators.",
    duration: "2 months",
    type: "Unpaid",
  },

  // Tourism - Events Management
  {
    id: "37",
    company: "Premier Event Management",
    majorId: "tourism",
    fieldId: "events-mgmt",
    major: "Tourism Service Business",
    field: "Events Management",
    location: "Jakarta, Indonesia",
    description: "Organize conferences, festivals, and events. Manage logistics and coordinate vendors.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "38",
    company: "Celebration Experts Events",
    majorId: "tourism",
    fieldId: "events-mgmt",
    major: "Tourism Service Business",
    field: "Events Management",
    location: "Bali, Indonesia",
    description: "Plan weddings, corporate events, and celebrations. Create memorable experiences.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "39",
    company: "Festival & Events Coordination",
    majorId: "tourism",
    fieldId: "events-mgmt",
    major: "Tourism Service Business",
    field: "Events Management",
    location: "Yogyakarta, Indonesia",
    description: "Coordinate cultural festivals and events. Handle budgeting and vendor management.",
    duration: "2 months",
    type: "Unpaid",
  },

  // Tourism - Customer Service
  {
    id: "40",
    company: "Hospitality Excellence",
    majorId: "tourism",
    fieldId: "customer-service",
    major: "Tourism Service Business",
    field: "Customer Service",
    location: "Jakarta, Indonesia",
    description: "Provide exceptional customer service to tourists. Handle inquiries and resolve issues.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "41",
    company: "Tourist Information Services",
    majorId: "tourism",
    fieldId: "customer-service",
    major: "Tourism Service Business",
    field: "Customer Service",
    location: "Bandung, Indonesia",
    description: "Assist tourists with information and booking. Ensure customer satisfaction and support.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "42",
    company: "Guest Relations Team",
    majorId: "tourism",
    fieldId: "customer-service",
    major: "Tourism Service Business",
    field: "Customer Service",
    location: "Medan, Indonesia",
    description: "Build relationships with guests and handle their needs. Provide multilingual support.",
    duration: "2 months",
    type: "Unpaid",
  },

  // Tourism - Destination Management
  {
    id: "43",
    company: "Destination Marketing Organization",
    majorId: "tourism",
    fieldId: "destination-mgmt",
    major: "Tourism Service Business",
    field: "Destination Management",
    location: "Jakarta, Indonesia",
    description: "Promote tourist destinations and develop tourism strategies. Manage destination partnerships.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "44",
    company: "Regional Tourism Development",
    majorId: "tourism",
    fieldId: "destination-mgmt",
    major: "Tourism Service Business",
    field: "Destination Management",
    location: "Bali, Indonesia",
    description: "Develop and manage tourist attractions. Work on infrastructure and visitor experiences.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "45",
    company: "Sustainable Destinations Agency",
    majorId: "tourism",
    fieldId: "destination-mgmt",
    major: "Tourism Service Business",
    field: "Destination Management",
    location: "Lombok, Indonesia",
    description: "Manage destination sustainability and community impact. Develop long-term tourism plans.",
    duration: "2 months",
    type: "Unpaid",
  },

  // Hotel Accommodation - Front Desk
  {
    id: "46",
    company: "Luxury Hotel Group",
    majorId: "hotel-accommodation",
    fieldId: "front-desk",
    major: "Hotel Accommodation",
    field: "Front Desk Operations",
    location: "Jakarta, Indonesia",
    description: "Manage front desk operations and guest check-ins. Handle reservations and inquiries.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "47",
    company: "Premium Hotels Indonesia",
    majorId: "hotel-accommodation",
    fieldId: "front-desk",
    major: "Hotel Accommodation",
    field: "Front Desk Operations",
    location: "Bali, Indonesia",
    description: "Provide excellent guest service at the front desk. Process bookings and manage keys.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "48",
    company: "Boutique Hotel Service",
    majorId: "hotel-accommodation",
    fieldId: "front-desk",
    major: "Hotel Accommodation",
    field: "Front Desk Operations",
    location: "Yogyakarta, Indonesia",
    description: "Welcome guests and manage reception services. Ensure smooth check-in and check-out.",
    duration: "2 months",
    type: "Unpaid",
  },

  // Hotel Accommodation - Housekeeping
  {
    id: "49",
    company: "Pristine Hotel Services",
    majorId: "hotel-accommodation",
    fieldId: "housekeeping",
    major: "Hotel Accommodation",
    field: "Housekeeping Management",
    location: "Jakarta, Indonesia",
    description: "Oversee housekeeping operations and room maintenance. Ensure cleanliness and comfort.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "50",
    company: "Five-Star Housekeeping",
    majorId: "hotel-accommodation",
    fieldId: "housekeeping",
    major: "Hotel Accommodation",
    field: "Housekeeping Management",
    location: "Bandung, Indonesia",
    description: "Manage housekeeping staff and room inspections. Maintain high quality standards.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "51",
    company: "Hotel Cleaning Excellence",
    majorId: "hotel-accommodation",
    fieldId: "housekeeping",
    major: "Hotel Accommodation",
    field: "Housekeeping Management",
    location: "Surabaya, Indonesia",
    description: "Ensure rooms meet high cleanliness standards. Learn about laundry and maintenance.",
    duration: "2 months",
    type: "Unpaid",
  },

  // Hotel Accommodation - Food & Beverage
  {
    id: "52",
    company: "Hotel Restaurant & Bar",
    majorId: "hotel-accommodation",
    fieldId: "food-beverage",
    major: "Hotel Accommodation",
    field: "Food & Beverage Service",
    location: "Jakarta, Indonesia",
    description: "Serve food and beverages in hotel restaurants. Provide excellent customer service.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "53",
    company: "Dining Excellence Hotel",
    majorId: "hotel-accommodation",
    fieldId: "food-beverage",
    major: "Hotel Accommodation",
    field: "Food & Beverage Service",
    location: "Bali, Indonesia",
    description: "Manage food and beverage service operations. Train staff and ensure guest satisfaction.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "54",
    company: "Hotel Culinary Services",
    majorId: "hotel-accommodation",
    fieldId: "food-beverage",
    major: "Hotel Accommodation",
    field: "Food & Beverage Service",
    location: "Yogyakarta, Indonesia",
    description: "Work in hotel restaurants and bars. Learn service standards and beverage knowledge.",
    duration: "2 months",
    type: "Unpaid",
  },

  // Hotel Accommodation - Hotel Management
  {
    id: "55",
    company: "Hotel Management Institute",
    majorId: "hotel-accommodation",
    fieldId: "hotel-mgmt",
    major: "Hotel Accommodation",
    field: "Hotel Management",
    location: "Jakarta, Indonesia",
    description: "Learn hotel management and operations. Work with management teams on hotel services.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "56",
    company: "Leading Hotels International",
    majorId: "hotel-accommodation",
    fieldId: "hotel-mgmt",
    major: "Hotel Accommodation",
    field: "Hotel Management",
    location: "Surabaya, Indonesia",
    description: "Manage hotel departments and staff. Ensure guest satisfaction and operational efficiency.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "57",
    company: "Professional Hotel Leaders",
    majorId: "hotel-accommodation",
    fieldId: "hotel-mgmt",
    major: "Hotel Accommodation",
    field: "Hotel Management",
    location: "Medan, Indonesia",
    description: "Develop hotel management skills and knowledge. Work on budgeting and planning.",
    duration: "2 months",
    type: "Unpaid",
  },

  // Hotel Accommodation - Guest Relations
  {
    id: "58",
    company: "Exceptional Guest Experience",
    majorId: "hotel-accommodation",
    fieldId: "guest-relations",
    major: "Hotel Accommodation",
    field: "Guest Relations",
    location: "Jakarta, Indonesia",
    description: "Build relationships with guests and handle special requests. Ensure memorable stays.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "59",
    company: "Premium Guest Services",
    majorId: "hotel-accommodation",
    fieldId: "guest-relations",
    major: "Hotel Accommodation",
    field: "Guest Relations",
    location: "Bali, Indonesia",
    description: "Manage guest satisfaction and loyalty programs. Provide concierge services.",
    duration: "3 months",
    type: "Paid",
  },
  {
    id: "60",
    company: "Hotel Guest Relations Team",
    majorId: "hotel-accommodation",
    fieldId: "guest-relations",
    major: "Hotel Accommodation",
    field: "Guest Relations",
    location: "Bandung, Indonesia",
    description: "Assist guests with requests and concerns. Build positive guest relationships.",
    duration: "2 months",
    type: "Unpaid",
  },
]
