// lib/models/mock_data.dart
import 'document_model.dart';

final List<DocumentModel> mockDocuments = [
  // MY DOCUMENTS - ACTIVE
  DocumentModel(
    id: '1',
    fileName: 'erd(2)',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.png,
    sizeKb: 86.0,
    dateModified: DateTime(2026, 2, 4),
    status: DocumentStatus.active,
    isStarred: true,
  ),
  DocumentModel(
    id: '2',
    fileName: 'MAGANG 2',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.pptx,
    sizeKb: 1638.4, // 1.6 MB
    dateModified: DateTime(2026, 2, 4),
    status: DocumentStatus.active,
    isStarred: true,
  ),
  DocumentModel(
    id: '3',
    fileName: 'CV_Dzaki_Prasetyo',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.pdf,
    sizeKb: 190.7,
    dateModified: DateTime(2026, 2, 4),
    status: DocumentStatus.active,
    isStarred: true,
  ),
  DocumentModel(
    id: '4',
    fileName: 'Nama Guru Mapel',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.xlsx,
    sizeKb: 7.1,
    dateModified: DateTime(2026, 2, 2),
    status: DocumentStatus.active,
    isStarred: false,
  ),
  DocumentModel(
    id: '5',
    fileName: 'Form Tugas Sebelum Magang 2025.1',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.xlsx,
    sizeKb: 23.8,
    dateModified: DateTime(2026, 2, 2),
    status: DocumentStatus.active,
    isStarred: false,
  ),
  DocumentModel(
    id: '6',
    fileName: 'CV_Fahrizal_Lautama',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.pdf,
    sizeKb: 190.7,
    dateModified: DateTime(2026, 2, 1),
    status: DocumentStatus.active,
    isStarred: false,
  ),
  DocumentModel(
    id: '7',
    fileName: 'CV_Dzaki_Prasetyo',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.pdf,
    sizeKb: 190.7,
    dateModified: DateTime(2026, 2, 1),
    status: DocumentStatus.active,
    isStarred: false,
  ),
  DocumentModel(
    id: '8',
    fileName: 'Laporan PKL Semester 5',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.docx,
    sizeKb: 245.3,
    dateModified: DateTime(2026, 1, 28),
    status: DocumentStatus.active,
    isStarred: false,
  ),
  DocumentModel(
    id: '9',
    fileName: 'Jadwal Pelajaran 2025',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.xlsx,
    sizeKb: 15.2,
    dateModified: DateTime(2026, 1, 25),
    status: DocumentStatus.active,
    isStarred: false,
  ),

  // ARCHIVES
  DocumentModel(
    id: '10',
    fileName: 'erd',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.png,
    sizeKb: 89.5,
    dateModified: DateTime(2026, 2, 4),
    status: DocumentStatus.archived,
    isStarred: false,
  ),
  DocumentModel(
    id: '11',
    fileName: 'DOC-20260120-WA0015',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.pdf,
    sizeKb: 190.7,
    dateModified: DateTime(2026, 2, 4),
    status: DocumentStatus.archived,
    isStarred: false,
  ),
  DocumentModel(
    id: '12',
    fileName: 'CV_Dzaki_Prasetyo-1',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.pdf,
    sizeKb: 190.7,
    dateModified: DateTime(2026, 2, 1),
    status: DocumentStatus.archived,
    isStarred: false,
  ),

  // TRASH / DELETED
  DocumentModel(
    id: '13',
    fileName: 'TUGAS MATEMATIKA KLS XI RPL',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.docx,
    sizeKb: 14.4,
    dateModified: DateTime(2026, 2, 4),
    status: DocumentStatus.deleted,
    isStarred: false,
  ),
  DocumentModel(
    id: '14',
    fileName: 'erd(1)',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.png,
    sizeKb: 125.3,
    dateModified: DateTime(2026, 2, 4),
    status: DocumentStatus.deleted,
    isStarred: false,
  ),
  DocumentModel(
    id: '15',
    fileName: 'CV_Dzaki_Prasetyo-1',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.pdf,
    sizeKb: 190.7,
    dateModified: DateTime(2026, 2, 2),
    status: DocumentStatus.deleted,
    isStarred: false,
  ),
  DocumentModel(
    id: '16',
    fileName: 'CV_Fahrizal_Lautama',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.pdf,
    sizeKb: 190.7,
    dateModified: DateTime(2026, 2, 2),
    status: DocumentStatus.deleted,
    isStarred: false,
  ),
  DocumentModel(
    id: '17',
    fileName: 'TUGAS MATEMATIKA KLS XI RPL',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.docx,
    sizeKb: 14.4,
    dateModified: DateTime(2026, 2, 2),
    status: DocumentStatus.deleted,
    isStarred: false,
  ),
  DocumentModel(
    id: '18',
    fileName: 'Proposal Skripsi Draft',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.docx,
    sizeKb: 312.5,
    dateModified: DateTime(2026, 1, 20),
    status: DocumentStatus.active,
    isStarred: false,
  ),
  DocumentModel(
    id: '19',
    fileName: 'Screenshot_UI_Design',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.png,
    sizeKb: 204.8,
    dateModified: DateTime(2026, 1, 18),
    status: DocumentStatus.active,
    isStarred: false,
  ),
  DocumentModel(
    id: '20',
    fileName: 'Budget Bulanan 2026',
    ownerName: 'Dzaki Prasetyo',
    ownerEmail: 'dzakiprasetyo98@gmail.com',
    ownerInitials: 'DP',
    extension: FileExtension.xlsx,
    sizeKb: 45.6,
    dateModified: DateTime(2026, 1, 15),
    status: DocumentStatus.active,
    isStarred: false,
  ),
];
